#!/bin/bash
# Backup CodeIgniter 3 database to a compressed file.

set -e #stop on error
set -o pipefail #stop on pipe error

# start of SETUP
config_path="/home/techxing/techxing.net/application/config"
# end of SETUP

backup_destination="$(dirname $(readlink -f $0))/backups" # absolute path of this script plus a backup folder
db_conf="${config_path}/database.php" # "/absolute/path/to/wordpress/.env"
db_name=$(grep "\$db\['default'\]\['hostname'\] = '[^']*[^']'" "${db_conf}" | cut -d "=" -f 2 | sed $'s/[^[:print:]\t]//;s/\'//g;s/ //;s/;//g')
db_user=$(grep "\$db\['default'\]\['username'\] = '[^']*[^']'" "${db_conf}" | cut -d "=" -f 2 | sed $'s/[^[:print:]\t]//;s/\'//g;s/ //;s/;//g')
db_pass=$(grep "\$db\['default'\]\['password'\] = '[^']*[^']'" "${db_conf}" | cut -d "=" -f 2 | sed $'s/[^[:print:]\t]//;s/\'//g;s/ //;s/;//g')
db_host=$(grep "\$db\['default'\]\['database'\] = '[^']*[^']'" "${db_conf}" | cut -d "=" -f 2 | sed $'s/[^[:print:]\t]//;s/\'//g;s/ //;s/;//g')

# Uncomment to show the variables extracted. The whole script will stop before doing the mysqldump.
# printf "VARS: \n\${db_conf} = '${db_conf}' \n\${db_name} = '${db_name}' \n\${db_user} = '${db_user}' \n\${db_pass} = '${db_pass}' \n\${db_host} = '${db_host}' \nDESTINATION: '${backup_destination}/${db_name}_$(date +%Y%m%d-%H%M%S).sql.gz' \n"; exit;

# MySQL / MariaDB.
/usr/bin/mysqldump -h "${db_host}" \
    -u "${db_user}" \
    -p"${db_pass}" \
    "${db_name}" \
    | gzip > "${backup_destination}/${db_name}_$(date +%Y%m%d-%H%M%S).sql.gz"